name: Auto Assign + Label

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Auto-assign
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: Web4application
        numOfAssignee: 1

    - name: Add label to issues
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: needs-triage
